import { SectionHeader } from "../components/SectionHeader";
import { logos } from "../data/siteContent";
import { useSiteContent } from "../hooks/useSiteContent";
import { useSEO } from "../hooks/useSEO";

export default function About() {
  useSEO({ title: "About Evolvix Tech Media", description: "Evolvix Tech Media is a Bardhaman-based AI and digital company helping people adapt, learn, create, and thrive through technology, creativity, and business tools.", path: "/about" });
  const { content } = useSiteContent();
  const about = content.about || {};
  const whatWeDo = about.what_we_do || [];
  const values = about.values?.length ? about.values : ["Clarity", "Creativity", "Innovation", "Accessibility", "Trust"];
  return <section className="section page-section" data-testid="about-page"><div className="page-hero" data-testid="about-hero"><div><span className="eyebrow">About / Vision</span><h1 data-testid="about-title">{about.title || "Humanizing the digital AI era."}</h1><p data-testid="about-intro">{about.intro || "Evolvix Tech Media exists because the future should not feel confusing, cold, or reserved for experts. It should feel approachable, useful, and creative for every age and skill level."}</p><p data-testid="about-description">{about.description}</p></div><img src={logos.icon} alt="Evolvix icon mark" data-testid="about-icon-logo" /></div><SectionHeader eyebrow="What We Do" title="Create. Build. Automate. Grow." /><div className="pillar-grid" data-testid="about-what-we-do-grid">{whatWeDo.map((item) => <article className="pillar-card" key={item.title} data-testid={`about-what-we-do-${item.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><div className="story-grid" data-testid="about-story-grid" style={{marginTop:"clamp(64px,8vw,96px)"}}><article><h2 data-testid="about-why-title">{about.why_title || "Why Evolvix exists"}</h2><p data-testid="about-why-text">{about.why_text || "The brand helps people cope with change, learn practical AI skills, discover useful digital products, and experience creative media that speaks to emotion and mood."}</p></article><article><h2 data-testid="about-mission-title">{about.mission_title || "The mission"}</h2><p data-testid="about-mission-text">{about.mission_text || "Simplify technology without reducing its power. Give students, professionals, parents, elderly users, and creators tools that make growth feel possible."}</p></article><article><h2 data-testid="about-creative-title">{about.creative_title || "The creative side"}</h2><p data-testid="about-creative-text">{about.creative_text || "AI music and mood-based digital expression bring feeling into the technology conversation, connecting calm, focus, nostalgia, energy, romance, and reflection."}</p></article></div><SectionHeader eyebrow="Values" title="A premium brand with a warm center." /><div className="value-grid" data-testid="about-values-grid">{values.map((value) => <span key={value} data-testid={`about-value-${value.toLowerCase()}`}>{value}</span>)}</div></section>;
}