import { useState } from "react";
import { Mic2, Music2, Play, Radio, WandSparkles } from "lucide-react";
import { musicMoods } from "../data/siteContent";
import { SectionHeader } from "../components/SectionHeader";
import { useSiteContent } from "../hooks/useSiteContent";

export default function CreativeLab() {
  const [selected, setSelected] = useState(musicMoods[0]);
  const { content } = useSiteContent();
  const musicServices = content.music_services || [];
  return <section className="section page-section lab-page" data-testid="creative-lab-page"><SectionHeader eyebrow="Music for Creators" title="AI background music for Reels, Shorts, TikTok, videos, podcasts, and digital storytelling." text="A creator-focused audio vertical for social media background tracks, mood-based music, brand themes, ambient sound, and audio identity." /><div className="music-service-grid" data-testid="music-services-grid">{musicServices.map((service) => <article className="service-card" key={service} data-testid={`music-service-${service.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}><Radio size={22} /><h3>{service}</h3><p>Premium creator audio direction for short-form content and brand storytelling.</p></article>)}</div><div className="lab-grid"><div className="mood-selector" data-testid="mood-selector">{musicMoods.map((item) => <button key={item.mood} className={selected.mood === item.mood ? "active" : ""} onClick={() => setSelected(item)} data-testid={`mood-select-${item.mood.toLowerCase()}-button`}><Music2 size={17} /> {item.mood}</button>)}</div><article className="sample-player" data-testid="sample-player-card"><span className="eyebrow" data-testid="selected-mood-eyebrow">Creator mood</span><h2 data-testid="selected-mood-title">{selected.mood}</h2><p data-testid="selected-mood-tone">{selected.tone}</p><button data-testid="sample-play-button"><Play size={18} /> Preview Direction</button><div className="wave-lines" data-testid="sample-wave-visual"><i></i><i></i><i></i><i></i><i></i></div></article><article className="creation-card" data-testid="create-by-mood-card"><Mic2 size={26} /><h2 data-testid="create-by-mood-title">Creator audio branding</h2><p data-testid="create-by-mood-text">For Reels, Shorts, TikTok, video intros, brand identity, podcast intros, and background storytelling tracks.</p><WandSparkles size={22} /></article></div></section>;
}