import { useState } from "react";
import { Mic2, Music2, Play, Radio, WandSparkles } from "lucide-react";
import { musicMoods } from "../data/siteContent";
import { SectionHeader } from "../components/SectionHeader";
import { useSiteContent } from "../hooks/useSiteContent";

export default function CreativeLab() {
  const [selected, setSelected] = useState(musicMoods[0]);
  const { content } = useSiteContent();
  const musicServices = content.music_services || [];
  const previews = (content.music_previews || []).filter((preview) => preview.visible !== false);
  const isDirectAudio = (url = "") => /\.(mp3|wav|ogg|m4a|aac)(\?|$)/i.test(url);
  return <section className="section page-section lab-page" data-testid="creative-lab-page"><SectionHeader eyebrow="Music for Creators" title="AI background music for Reels, Shorts, TikTok, videos, podcasts, and digital storytelling." text="A creator-focused audio vertical for social media background tracks, mood-based music, brand themes, ambient sound, and audio identity." /><div className="music-service-grid" data-testid="music-services-grid">{musicServices.map((service) => <article className="service-card" key={service} data-testid={`music-service-${service.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}><Radio size={22} /><h3>{service}</h3><p>Premium creator audio direction for short-form content and brand storytelling.</p></article>)}</div>{previews.length > 0 && <div className="audio-preview-grid" data-testid="audio-preview-grid">{previews.map((preview, index) => <article className="audio-preview-card" key={preview.id || `${preview.title}-${index}`} data-testid={`audio-preview-card-${index}`}><span data-testid={`audio-preview-mood-${index}`}>{preview.mood}</span><h3 data-testid={`audio-preview-title-${index}`}>{preview.title}</h3><p data-testid={`audio-preview-description-${index}`}>{preview.description}</p>{preview.audio_url ? (isDirectAudio(preview.audio_url) ? <audio controls src={preview.audio_url} data-testid={`audio-preview-player-${index}`}>Audio preview</audio> : <a className="audio-preview-placeholder" href={preview.audio_url} target="_blank" rel="noreferrer" data-testid={`audio-preview-external-link-${index}`}><Play size={18} /> Open music preview</a>) : <div className="audio-preview-placeholder" data-testid={`audio-preview-placeholder-${index}`}><Play size={18} /> Preview file coming soon</div>}</article>)}</div>}<div className="lab-grid"><div className="mood-selector" data-testid="mood-selector">{musicMoods.map((item) => <button key={item.mood} className={selected.mood === item.mood ? "active" : ""} onClick={() => setSelected(item)} data-testid={`mood-select-${item.mood.toLowerCase()}-button`}><Music2 size={17} /> {item.mood}</button>)}</div><article className="sample-player" data-testid="sample-player-card"><span className="eyebrow" data-testid="selected-mood-eyebrow">Creator mood</span><h2 data-testid="selected-mood-title">{selected.mood}</h2><p data-testid="selected-mood-tone">{selected.tone}</p><button data-testid="sample-play-button"><Play size={18} /> Preview Direction</button><div className="wave-lines" data-testid="sample-wave-visual"><i></i><i></i><i></i><i></i><i></i></div></article><article className="creation-card" data-testid="create-by-mood-card"><Mic2 size={26} /><h2 data-testid="create-by-mood-title">Creator audio branding</h2><p data-testid="create-by-mood-text">For Reels, Shorts, TikTok, video intros, brand identity, podcast intros, and background storytelling tracks.</p><WandSparkles size={22} /></article></div></section>;
}